#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@adbyby[-1]
	add ucitrack adbyby
	set ucitrack.@adbyby[-1].init=adbyby
	commit ucitrack
	delete firewall.adbyby
	set firewall.adbyby=include
	set firewall.adbyby.type=script
	set firewall.adbyby.path=/var/etc/adbyby.include
	set firewall.adbyby.reload=1
	delete firewall.adblock
  add firewall rule
  rename firewall.@rule[-1]="adblock"
  set firewall.@rule[-1].name="adblock"
  set firewall.@rule[-1].target="DROP"
  set firewall.@rule[-1].src="wan"
  set firewall.@rule[-1].proto="tcp"
  set firewall.@rule[-1].dest_port="8118"
	commit firewall
EOF

mkdir -p /etc/dnsmasq.d

chmod 0775 /usr/share/adbyby/* >/dev/null 2>&1
chmod 0775 /etc/init.d/adbyby >/dev/null 2>&1
/etc/init.d/adbyby stop >/dev/null 2>&1
/etc/init.d/adbyby enable
rm -f /usr/share/adbyby/luciver.txt >/dev/null 2>&1
rm -f /tmp/luci-indexcache*
exit 0
